theme: jekyll-theme-minimal
title: Welcome!
description: DSN's minimalist home page.  Contact at initialsinlowercase@vt.edu, or at x14260, or in person. I shun social media.
position: Professor
affiliation: Virginia Tech
email: dsn@vt.edu
logo: C92A3B0D-BF1A-49E4-A51B-F4E21841AAD9_1_105_c.jpeg
github:
    is_user_page: false
kramdown:
    input: Kramdown
