theme: 
title: Dimitrios S. Nikolopoulos
position: Professor
affiliation: Virginia Tech
email: dsn@vt.edu
description: 
logo: C92A3B0D-BF1A-49E4-A51B-F4E21841AAD9_1_105_c.jpeg
github:
  is_project_page: false

